name: "Get APT package version"
description: "Get candidate package version in an Ubuntu/Debian APT repo"
branding:
  icon: package
  color: orange
inputs:
  baseImage:
    description: "Ubuntu/Debian based image to use"
    required: true
    default: "ubuntu:focal"
  package:
    description: "Package to look for"
    required: true
  ppa:
    description: "Additional PPA repository"
    required: false
outputs:
  version:
    description: "The version of the package"
    value: ${{ steps.run.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: build
      run: docker build --build-arg BASE_IMAGE=${{ inputs.baseImage }} -t apt-package-version ./get-apt-package-version
      shell: bash
    - id: run
      run: docker run --rm -v $(pwd):/github/workspace --workdir /github/workspace apt-package-version ${{ inputs.ppa && format('-p {0}', inputs.ppa) }} ${{ inputs.package }}
      shell: bash
