name: "Get APT package version"
description: "Get candidate package version in an Ubuntu/Debian APT repo"
branding:
  icon: package
  color: orange
inputs:
  baseImage:
    description: "Ubuntu/Debian based image to use"
    required: true
    default: "ubuntu:focal"
  package:
    description: "Package to look for"
    required: true
  ppa:
    description: "Additional PPA repository"
    required: false
outputs:
  version:
    description: "The version of the package"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "${{ inputs.baseImage }}"
    - "${{ inputs.ppa && '-p' }}"
    - "${{ inputs.ppa }}"
    - "${{ inputs.package }}"
